export const FORM_DATA_CONST = {
  ADD_ANOTHER_EMAIL: 'ADD_ANOTHER_EMAIL',
  UPDATE_EMAIL_DATA: 'UPDATE_EMAIL_DATA',
  REMOVE_EMAIL: 'REMOVE_EMAIL',
  UPDATE_CAMPAIGN_NAME: 'UPDATE_CAMPAIGN_NAME',
  ADD_FILE: 'ADD_FILE',
  RESET_FORM: 'RESET_FORM'
};